logging:
  level:
    sql: debug
    web: debug
    '[com.redmath]': debug
  pattern:
    level: "%5p ${HOSTNAME}"


spring:
  application:
    name: bank
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    url: ${bank.db.url}
    username: ${bank.db.username}
    password: ${bank.db.password}
  h2:
    console:
      enabled: ${bank.h2.console:false}
  liquibase:
    contexts: ${bank.liquibase.contexts:}

  management:
    endpoints:
      web:
        exposure:
          include: '*'
    endpoint:
      health:
        show-details: when-authorized


spring.profiles.include: dev
